on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.virtualbox.VirtualBox-KVM
        manifest-path: org.virtualbox.VirtualBox-KVM.yml
        cache: true
        restore-cache: true
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: /run/build/virtualbox/configure.log
